package contribute

import "fmt"

// OriginConfig describes the remote origin that serves relayed guests.
//
// It runs the SAME MediaMTX binary this Mac already ships, with the same stream
// geometry, so relayed guests get a byte-identical LL-HLS surface to direct
// guests: native AVPlayer, plain HTTPS GETs, and lock-screen playback unchanged.
// Nothing about the playback engine differs between modes.
type OriginConfig struct {
	RTSPPort int    // contribution ingest, public
	HLSPort  int    // guest delivery, public
	CertPath string // wildcard cert covering the relay hostname
	KeyPath  string
	SegCount int
	SegDur   string
	PartDur  string
	Path     string // room path; one per Mac
}

// OriginYAML renders the origin's mediamtx.yml.
//
// It differs from the Mac's local config in exactly two ways, both required and
// both deliberate: it binds publicly rather than to loopback, and it demands a
// publish credential. Everything about the media, segment count, segment and
// part duration, and low-latency variant, is identical, because relayed guests
// must not get a different stream shape from direct ones.
//
// Read is deliberately left unauthenticated: guests have no account, and gating
// a guest route on credentials is the one thing this product never does.
func OriginYAML(o OriginConfig, publishUser, publishPass string) string {
	return fmt.Sprintf(`# Generated by partyparty. Do not edit by hand.
api: no
metrics: no
playback: no
rtmp: no
srt: no
webrtc: no
moq: no
rtsp: yes
rtspAddress: :%d
rtspTransports: [tcp]
hls: yes
hlsAddress: :%d
hlsEncryption: yes
hlsServerCert: %s
hlsServerKey: %s
hlsVariant: lowLatency
hlsAlwaysRemux: yes
hlsSegmentCount: %d
hlsSegmentDuration: %s
hlsPartDuration: %s
hlsAllowOrigins: ['*']
authInternalUsers:
- user: %s
  pass: %s
  permissions:
  - action: publish
- user: any
  pass:
  permissions:
  - action: read
paths:
  %s:
`, o.RTSPPort, o.HLSPort, o.CertPath, o.KeyPath, o.SegCount, o.SegDur, o.PartDur, publishUser, publishPass, o.Path)
}
