-- A track can be a picture of one.
--
-- Owner, 2026-08-09: "I can definitely see myself taking screenshots of what is
-- being shazamed at the party and then wanting to upload them here. In fact I
-- think that's better than me typing to input in the field."
--
-- So a song row is either typed (title, artist) or shot (media_key), and a shot
-- one needs no title at all - the picture is the record. Nullable rather than
-- defaulted: "no picture" and "a picture whose key is empty string" are not the
-- same thing, and only one of them should ever exist.
ALTER TABLE songs ADD COLUMN media_key TEXT;
